services:
  mcp-exa:
    image: mcp/exa
    container_name: mcp-exa-central
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - EXA_API_KEY=${EXA_API_KEY}

  mcp-memory:
    image: mcp/memory
    container_name: mcp-memory-central
    restart: unless-stopped
    stdin_open: true
    tty: true

  mcp-sentry:
    image: mcp/sentry
    container_name: mcp-sentry-central
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    command: --auth-token "${SENTRY_AUTH_TOKEN}"

  mcp-playwright:
    image: mcp/playwright
    container_name: mcp-playwright-central
    restart: unless-stopped
    stdin_open: true
    tty: true

  mcp-context7:
    image: mcp/context7
    container_name: mcp-context7-central
    restart: unless-stopped
    stdin_open: true
    tty: true

  mcp-github:
    image: mcp/github
    container_name: mcp-github-central
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}

  mcp-filesystem:
    image: mcp/filesystem
    container_name: mcp-filesystem-central
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/viniciusfigueiredo/Documentos/Projetos/:/projects:ro
    command: ["/projects"]

  mcp-dockerhub:
    image: mcp/dockerhub
    container_name: mcp-dockerhub-central
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mcp-fetch:
    image: mcp/fetch
    container_name: mcp-fetch-central
    restart: unless-stopped
    stdin_open: true
    tty: true

  mcp-sequential-thinking:
    image: mcp/sequentialthinking
    container_name: mcp-sequential-thinking-central
    restart: unless-stopped
    stdin_open: true
    tty: true
